version: '1.0'

services:
  frontend:
    build: ./web
    container_name: data_export_frontend
    environment:
      - REACT_APP_API_URL
      - REACT_APP_AUTH_URL
      - REACT_APP_PROTECTED_URL
      - X_API_KEY
    ports:
      - "${WEB_LOCAL_PORT}:3000"

  api:
    build: ./node-rest-api
    container_name: data_export_api
    environment:
      - CONVERTER_PORT
      - AUTH_PORT
      - DB_PORT
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_DATABASE
      - SQLPATH
      - CF_MYSQL_URL
      - XLSXPassword
      - SECRET_KEY
      - ACCOUNT_USERNAME
      - ACCOUNT_PASSWORD
      - X_API_KEY
    ports:
      - '${API_LOCAL_PORT}:8000'  